# Generated by Django 5.1.5 on 2025-02-18 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='history_user',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_telegra_b51e4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_role_36d76d_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_type_3fc058_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='tariff',
            field=models.CharField(blank=True, choices=[('standard', 'Standard Pro'), ('vip', 'VIP Pro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('carrier', 'Carrier'), ('cargo-owner', 'Cargo Owner'), ('logistics-company', 'Logistics Company'), ('transport-company', 'Transport Company'), ('logit-trans', 'Logit Trans'), ('manager', 'Manager')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalUser',
        ),
    ]
