# Generated by Django 5.1.5 on 2025-02-24 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.SmallIntegerField(choices=[(1, 'Country'), (2, 'State/Region'), (3, 'City')])),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('additional_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_locations', to='core.location')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.location')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['level'], name='core_locati_level_ad3de4_idx'), models.Index(fields=['parent_id'], name='core_locati_parent__d3129b_idx'), models.Index(fields=['country_id'], name='core_locati_country_af60fe_idx'), models.Index(fields=['latitude', 'longitude'], name='location_coords_idx')],
            },
        ),
    ]
