# Generated by Django 5.1.5 on 2025-01-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Notes about vehicle verification', null=True),
        ),
    ]
