# Generated by Django 5.1.5 on 2025-01-31 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargodocument',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cargo.cargo'),
        ),
        migrations.AddField(
            model_name='cargostatushistory',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='cargo.cargo'),
        ),
        migrations.AddField(
            model_name='cargostatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['status'], name='cargo_cargo_status_306572_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['loading_date'], name='cargo_cargo_loading_ca23cc_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['owner'], name='cargo_cargo_owner_i_3f0b64_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['source_type', 'source_id'], name='cargo_cargo_source__d72990_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['vehicle_type'], name='cargo_cargo_vehicle_801372_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['loading_point'], name='cargo_cargo_loading_36d4cb_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['unloading_point'], name='cargo_cargo_unloadi_283c75_idx'),
        ),
    ]
