# Generated by Django 5.1.5 on 2025-02-09 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_initial'),
        ('vehicles', '0002_vehicle_verification_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_point', models.CharField(max_length=255)),
                ('unloading_point', models.CharField(max_length=255)),
                ('ready_date', models.DateField()),
                ('vehicle_count', models.PositiveIntegerField(default=1)),
                ('price_expectation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned to Cargo'), ('accepted', 'Accepted by Carrier'), ('rejected', 'Rejected by Carrier'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'carrier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cargos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargo',
            name='managed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_cargos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_cargos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Assignment'), ('assigned', 'Assigned to Carrier'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='cargostatushistory',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Assignment'), ('assigned', 'Assigned to Carrier'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['assigned_to'], name='cargo_cargo_assigne_efacb7_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['managed_by'], name='cargo_cargo_managed_9919ee_idx'),
        ),
        migrations.AddField(
            model_name='carrierrequest',
            name='assigned_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_carrier_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carrierrequest',
            name='assigned_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_requests', to='cargo.cargo'),
        ),
        migrations.AddField(
            model_name='carrierrequest',
            name='carrier',
            field=models.ForeignKey(limit_choices_to={'role': 'carrier'}, on_delete=django.db.models.deletion.CASCADE, related_name='carrier_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carrierrequest',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_requests', to='vehicles.vehicle'),
        ),
        migrations.AddIndex(
            model_name='carrierrequest',
            index=models.Index(fields=['carrier'], name='cargo_carri_carrier_9aec82_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierrequest',
            index=models.Index(fields=['status'], name='cargo_carri_status_87fdd6_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierrequest',
            index=models.Index(fields=['ready_date'], name='cargo_carri_ready_d_338485_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierrequest',
            index=models.Index(fields=['loading_point'], name='cargo_carri_loading_9e25b1_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierrequest',
            index=models.Index(fields=['unloading_point'], name='cargo_carri_unloadi_a5dd68_idx'),
        ),
    ]
