# Generated by Django 5.1.5 on 2025-02-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_carrierrequest_cargo_assigned_to_cargo_managed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='source_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='source_type',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('api', 'External API'), ('manual', 'Manual Entry'), ('website', 'Website')], default='manual', max_length=20),
        ),
    ]
