# Generated by Django 5.1.5 on 2025-02-24 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0005_cargo_approval_date_cargo_approval_notes_and_more'),
        ('core', '0003_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='additional_locations',
            field=models.ManyToManyField(blank=True, null=True, related_name='intermediate_cargos', to='core.location'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='loading_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loading_cargos', to='core.location'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='unloading_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unloading_cargos', to='core.location'),
        ),
    ]
