# Generated by Django 5.1.5 on 2025-02-25 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0007_alter_cargo_owner'),
        ('core', '0004_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrierrequest',
            name='loading_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_loading_requests', to='core.location'),
        ),
        migrations.AddField(
            model_name='carrierrequest',
            name='unloading_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_unloading_requests', to='core.location'),
        ),
    ]
